import { useEffect, useState } from "react";
import { 
  WarRoomState, 
  RegulationObject, 
  ActionPoint, 
  DriftAlert 
} from "./types";
import DigitalTwin from "./components/DigitalTwin";
import DriftMonitoring from "./components/DriftMonitoring";
import LiveFeed from "./components/LiveFeed";
import RiskPredictor from "./components/RiskPredictor";
import { 
  Shield, 
  Settings, 
  Users, 
  Workflow, 
  Activity, 
  Database,
  Briefcase,
  Layers,
  CheckSquare,
  AlertOctagon,
  RefreshCw,
  Clock,
  ExternalLink,
  Bot
} from "lucide-react";

export default function App() {
  const [state, setState] = useState<WarRoomState | null>(null);
  const [regulations, setRegulations] = useState<RegulationObject[]>([]);
  const [selectedReg, setSelectedReg] = useState<RegulationObject | null>(null);
  const [allActionPoints, setAllActionPoints] = useState<ActionPoint[]>([]);
  const [activeTab, setActiveTab] = useState<"war-room" | "map-dashboard" | "twin-viz">("war-room");
  const [isInitializing, setIsInitializing] = useState(true);

  // Initial Fetch to mount simulated data
  useEffect(() => {
    async function initDashboard() {
      try {
        const response = await fetch("/api/systems-state");
        const data = await response.json();
        
        setState(data.systems);
        setRegulations(data.regulations);
        
        // Pick the first circular to show initially
        if (data.regulations.length > 0) {
          setSelectedReg(data.regulations[0]);
        }

        // Aggregate action points from pre-loaded circular entries
        const aggregated: ActionPoint[] = [];
        data.regulations.forEach((reg: RegulationObject) => {
          if (reg.parsed?.actionPoints) {
            aggregated.push(...reg.parsed.actionPoints);
          }
        });
        setAllActionPoints(aggregated);
      } catch (e) {
        console.error("Initiation failed:", e);
      } finally {
        setIsInitializing(false);
      }
    }
    initDashboard();
  }, []);

  // Action: Add fresh regulation generated by Gemini
  const handleAddRegulation = (newReg: RegulationObject) => {
    setRegulations((prev) => [newReg, ...prev]);
    
    // Add fresh MAP action points onto active lists
    if (newReg.parsed?.actionPoints) {
      setAllActionPoints((prev) => [...newReg.parsed.actionPoints, ...prev]);
    }

    // Dynamic risk propagation calculations!
    if (state) {
      const riskImpact = newReg.parsed?.predictiveRiskIncrease || 15;
      
      // Update nodes in twins state that were impacted by this circular
      const updatedNodes = state.digitalTwin.nodes.map(node => {
        const matchingImpactObj = newReg.parsed.twinImpact.find(impact => impact.systemName === node.id);
        if (matchingImpactObj) {
          return {
            ...node,
            status: node.status === "HEALTHY" ? "WARNING" as const : "CRITICAL" as const
          };
        }
        return node;
      });

      // Compose high value risk factors from the circular
      const newRiskFactors = [
        `Outstanding requirements for ${newReg.title}`,
        ...state.predictiveInsights.riskFactors
      ];

      // Update War Room State
      setState((prev) => {
        if (!prev) return null;
        return {
          ...prev,
          overallRiskScore: Math.min(prev.overallRiskScore + Math.floor(riskImpact / 2), 100),
          statusSummary: `WARNING - Posture under adjustment for incoming ${newReg.authority} regulations`,
          digitalTwin: {
            ...prev.digitalTwin,
            nodes: updatedNodes
          },
          predictiveInsights: {
            ...prev.predictiveInsights,
            failureProbability: Math.min(prev.predictiveInsights.failureProbability + Math.floor(riskImpact / 3), 100),
            riskFactors: newRiskFactors.slice(0, 4)
          }
        };
      });
    }
  };

  // Action: Inject Drift simulated scenario
  const handleTriggerDrift = (nodeId: string) => {
    if (!state) return;

    // Determine target mock drift attributes based on system clicked
    const targetDrift: DriftAlert = {
      id: `drift-${Date.now()}`,
      system: nodeId,
      control: "Cryptographic Consent SLAs" ,
      expected: "Policy constraint actively logs requests",
      actual: "0% active checking (Control bypassed by DevOps thread)",
      severity: "CRITICAL",
      detectedAt: new Date().toISOString(),
      driftDays: 1,
      remedyAction: "Enforce boundary firewall logs and restore strict API validation parameters"
    };

    // Update state variables to reflect the breach
    setState((prev) => {
      if (!prev) return null;
      
      const updatedNodes = prev.digitalTwin.nodes.map(node => 
        node.id === nodeId ? { ...node, status: "CRITICAL" as const } : node
      );

      return {
        ...prev,
        overallRiskScore: Math.min(prev.overallRiskScore + 18, 100),
        activeDrifts: [targetDrift, ...prev.activeDrifts],
        digitalTwin: {
          ...prev.digitalTwin,
          nodes: updatedNodes
        },
        predictiveInsights: {
          ...prev.predictiveInsights,
          failureProbability: Math.min(prev.predictiveInsights.failureProbability + 12, 100),
          riskFactors: [`Unresolved governance drift observed in core ${nodeId} layers`, ...prev.predictiveInsights.riskFactors]
        }
      };
    });
  };

  // Action: Recover Drift/Clear Drift manual trigger
  const handleClearDrift = (nodeId: string) => {
    if (!state) return;

    setState((prev) => {
      if (!prev) return null;

      const updatedNodes = prev.digitalTwin.nodes.map(node => 
        node.id === nodeId ? { ...node, status: "HEALTHY" as const } : node
      );

      const cleanedDrifts = prev.activeDrifts.filter(drift => drift.system !== nodeId);

      return {
        ...prev,
        overallRiskScore: Math.max(prev.overallRiskScore - 15, 10),
        activeDrifts: cleanedDrifts,
        digitalTwin: {
          ...prev.digitalTwin,
          nodes: updatedNodes
        },
        predictiveInsights: {
          ...prev.predictiveInsights,
          failureProbability: Math.max(prev.predictiveInsights.failureProbability - 10, 20),
          riskFactors: prev.predictiveInsights.riskFactors.filter(factor => !factor.includes(nodeId))
        }
      };
    });
  };

  // Action: Action Point Task Completer Game Mechanics!
  const toggleActionItemStatus = (jiraTicket: string) => {
    const updated = allActionPoints.map((ap) => {
      if (ap.jiraTicket === jiraTicket) {
        const nextStatus = ap.status === "COMPLETED" ? "IN_PROGRESS" as const : "COMPLETED" as const;
        return { ...ap, status: nextStatus };
      }
      return ap;
    });

    setAllActionPoints(updated);

    // Calculate dynamic risk reduction for completing MAP action items!
    if (state) {
      const isFinishing = updated.find(a => a.jiraTicket === jiraTicket)?.status === "COMPLETED";
      setState((prev) => {
        if (!prev) return null;
        return {
          ...prev,
          overallRiskScore: isFinishing ? Math.max(prev.overallRiskScore - 4, 10) : Math.min(prev.overallRiskScore + 4, 100),
          predictiveInsights: {
            ...prev.predictiveInsights,
            failureProbability: isFinishing 
              ? Math.max(prev.predictiveInsights.failureProbability - 5, 15) 
              : Math.min(prev.predictiveInsights.failureProbability + 5, 100)
          }
        };
      });
    }
  };

  // Action: Action playbook completed from drift component
  const handleRemediateAlert = (alertId: string) => {
    if (!state) return;
    const alertObj = state.activeDrifts.find(d => d.id === alertId);
    if (alertObj) {
      handleClearDrift(alertObj.system);
    }
  };

  if (isInitializing) {
    return (
      <div className="min-h-screen bg-[#09090B] flex flex-col items-center justify-center p-6 text-zinc-100 font-sans" id="app-loading">
        <div className="w-12 h-12 rounded-full border-4 border-blue-500/30 border-t-blue-500 animate-spin mb-4" />
        <h3 className="text-lg font-medium text-white tracking-widest font-mono uppercase text-center">CONNECTING SECURE COMPLIANCE FABRIC...</h3>
        <p className="text-xs text-zinc-500 mt-2">Initializing SentinelX AI Regulatory Core Infrastructure</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#09090B] text-zinc-100 font-sans pb-12 overflow-x-hidden" id="sentinelx-core-root">
      
      {/* Top Navigation Bar HUD (Slide 10 War Room design targets) */}
      <header className="border-b border-zinc-800 bg-[#0C0C0E]/90 backdrop-blur sticky top-0 z-40 px-6 py-4" id="hud-header">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-lg bg-blue-600 text-white shadow-md shadow-blue-500/30 font-bold text-lg">
              Ω
            </div>
            <div>
              <div className="flex items-center gap-2">
                <span className="text-[10px] font-mono tracking-widest font-bold text-blue-400 uppercase bg-blue-950/40 px-2 py-0.5 rounded border border-blue-800/20">
                  SYSTEM LEVEL: EXECUTIVE SECURE
                </span>
                <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
              </div>
              <h1 className="text-2xl font-sans font-semibold text-white tracking-tight mt-0.5">
                SENTINELX <span className="text-zinc-500 font-light">AI</span>
              </h1>
            </div>
          </div>

          {/* Central Ribbon Navigation tabs */}
          <div className="flex items-center gap-1.5 bg-zinc-900/40 p-1 border border-zinc-800 rounded-lg">
            <button
              onClick={() => setActiveTab("war-room")}
              className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-xs font-bold font-mono uppercase tracking-wider transition-all cursor-pointer ${activeTab === "war-room" ? "bg-zinc-800 border border-zinc-700 text-white" : "text-zinc-400 hover:text-white"}`}
              id="tab-war-room"
            >
              <Activity className="w-4 h-4 text-blue-500" />
              War Room Feed
            </button>
            <button
              onClick={() => setActiveTab("map-dashboard")}
              className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-xs font-bold font-mono uppercase tracking-wider transition-all cursor-pointer ${activeTab === "map-dashboard" ? "bg-zinc-800 border border-zinc-700 text-white" : "text-zinc-400 hover:text-white"}`}
              id="tab-map-dashboard"
            >
              <CheckSquare className="w-4 h-4 text-blue-500" />
              MAP Database
            </button>
            <button
              onClick={() => setActiveTab("twin-viz")}
              className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-xs font-bold font-mono uppercase tracking-wider transition-all cursor-pointer ${activeTab === "twin-viz" ? "bg-zinc-800 border border-zinc-700 text-white" : "text-zinc-400 hover:text-white"}`}
              id="tab-twin"
            >
              <Workflow className="w-4 h-4 text-blue-500" />
              Twin Topology
            </button>
          </div>

          <div className="flex items-center gap-4 text-xs font-mono">
            <div className="bg-zinc-900/50 border border-zinc-800 px-3 py-2 rounded-lg flex items-center gap-2">
              <Bot className="w-4 h-4 text-blue-400 animate-pulse" />
              <span className="text-zinc-500 uppercase">Gemini:</span>
              <span className="text-white font-bold">gemini-3.5-flash</span>
            </div>
          </div>
        </div>
      </header>

      {/* Main War Room Body viewport */}
      <main className="max-w-7xl mx-auto px-6 mt-8 flex flex-col gap-8" id="hud-viewport">
        
        {/* Top Stats Overview Panel Row */}
        {state && (
          <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4" id="stats-dashboard">
            <div className="bg-zinc-900/40 border border-zinc-800 rounded-2xl p-5 shadow-lg flex items-center justify-between relative overflow-hidden">
              <div className="absolute top-0 right-0 w-16 h-16 bg-blue-500/5 rounded-full filter blur-xl" />
              <div>
                <span className="text-[10px] font-mono font-bold text-zinc-500 uppercase tracking-widest">POSTURE RISK SCORE</span>
                <div className="text-3xl font-mono font-bold text-white mt-1.5">{state.overallRiskScore}%</div>
                <div className="mt-1">
                  {state.overallRiskScore > 50 ? (
                    <span className="text-[10px] text-rose-400 font-mono">▲ HIGH RISK ELEVATION</span>
                  ) : state.overallRiskScore > 30 ? (
                    <span className="text-[10px] text-orange-400 font-mono">■ MODERATE posture risk limit</span>
                  ) : (
                    <span className="text-[10px] text-emerald-400 font-mono">▲ SECURE limit boundaries</span>
                  )}
                </div>
              </div>
              <div className="p-3 bg-zinc-900 rounded-lg border border-zinc-800">
                <Layers className={`w-5 h-5 ${state.overallRiskScore > 50 ? "text-rose-500 animate-pulse" : "text-blue-500"}`} />
              </div>
            </div>

            <div className="bg-zinc-900/40 border border-zinc-800 rounded-2xl p-5 shadow-lg flex items-center justify-between relative overflow-hidden">
              <div className="absolute top-0 right-0 w-16 h-16 bg-rose-500/5 rounded-full filter blur-xl" />
              <div>
                <span className="text-[10px] font-mono font-bold text-zinc-500 uppercase tracking-widest">ACTIVE DRIFT CONCERNS</span>
                <div className="text-3xl font-mono font-bold text-white mt-1.5">{state.activeDrifts.length}</div>
                <div className="text-[10px] text-rose-400 font-mono mt-1">
                  {state.activeDrifts.length > 0 ? "⚠️ Playbook remedy available" : "✓ Telemetry perfectly aligned"}
                </div>
              </div>
              <div className="p-3 bg-zinc-900 rounded-lg border border-zinc-800">
                <AlertOctagon className={`w-5 h-5 ${state.activeDrifts.length > 0 ? "text-rose-400 animate-bounce" : "text-emerald-400"}`} />
              </div>
            </div>

            <div className="bg-zinc-900/40 border border-zinc-800 rounded-2xl p-5 shadow-lg flex items-center justify-between relative overflow-hidden">
              <div className="absolute top-0 right-0 w-16 h-16 bg-indigo-500/5 rounded-full filter blur-xl" />
              <div>
                <span className="text-[10px] font-mono font-bold text-zinc-500 uppercase tracking-widest">INGESTED REGULATION FILED</span>
                <div className="text-3xl font-mono font-bold text-white mt-1.5">{regulations.length}</div>
                <div className="text-[10px] text-zinc-400 font-mono mt-1">
                  Continuous portal sweep online
                </div>
              </div>
              <div className="p-3 bg-zinc-900 rounded-lg border border-zinc-800">
                <Database className="w-5 h-5 text-indigo-400" />
              </div>
            </div>

            <div className="bg-zinc-900/40 border border-zinc-800 rounded-2xl p-5 shadow-lg flex items-center justify-between relative overflow-hidden">
              <div className="absolute top-0 right-0 w-16 h-16 bg-emerald-500/5 rounded-full filter blur-xl" />
              <div>
                <span className="text-[10px] font-mono font-bold text-zinc-500 uppercase tracking-widest">Remediation MAP Tasks</span>
                <div className="text-3xl font-mono font-bold text-white mt-1.5">
                  {allActionPoints.filter(a => a.status === "COMPLETED").length}/{allActionPoints.length}
                </div>
                <div className="text-[10px] text-emerald-400 font-mono mt-1">
                  ({Math.floor((allActionPoints.filter(a => a.status === "COMPLETED").length / (allActionPoints.length || 1)) * 100)}% implementation status)
                </div>
              </div>
              <div className="p-3 bg-zinc-900 rounded-lg border border-zinc-800">
                <Briefcase className="w-5 h-5 text-emerald-400" />
              </div>
            </div>
          </section>
        )}

        {/* Dynamic Inner Tab Router */}
        {activeTab === "war-room" && state && (
          <div className="flex flex-col gap-8 transition-all animate-fade-in" id="war-room-view">
            
            {/* Row 1: Interactive Virtual Digital Twin modeling interface */}
            <DigitalTwin 
              nodes={state.digitalTwin.nodes} 
              links={state.digitalTwin.links}
              onTriggerDrift={handleTriggerDrift}
              onClearDrift={handleClearDrift}
            />

            {/* Row 2: Regulatory Intelligence Feed scanner */}
            <LiveFeed 
              regulations={regulations}
              onAddRegulation={handleAddRegulation}
              selectedReg={selectedReg}
              onSelectReg={setSelectedReg}
            />

            {/* Row 3: Live compliance drift anomalies panel */}
            <DriftMonitoring 
              alerts={state.activeDrifts}
              onRemediate={handleRemediateAlert}
            />

            {/* Row 4: Predictive risk circular matrix metrics */}
            <RiskPredictor 
              insights={state.predictiveInsights}
              score={state.overallRiskScore}
              activeDrifts={state.activeDrifts}
            />
          </div>
        )}

        {/* MAP Action point Database checklist */}
        {activeTab === "map-dashboard" && (
          <div className="bg-zinc-900/40 border border-zinc-800 rounded-2xl p-6 shadow-2xl transition-all animate-fade-in" id="map-database-view">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-zinc-800 pb-4 mb-6">
              <div>
                <span className="text-xs font-mono font-bold text-blue-400 uppercase tracking-wider block">MITIGATION ACTION ACTION DATABASE</span>
                <h3 className="text-xl font-sans font-semibold text-white mt-0.5">
                  Corporate MAP Implementation Dashboard
                </h3>
                <p className="text-xs text-zinc-400 mt-1">
                  Direct list of system implementations generated by parsing regulatory documents. Mark completed items to reduce system risks!
                </p>
              </div>
              <div className="flex items-center gap-3 bg-zinc-950 px-4 py-2 rounded-lg border border-zinc-800 text-xs font-mono text-zinc-400">
                <div>Outstanding tickets:</div>
                <div className="text-lg font-bold text-rose-500">{allActionPoints.filter(a => a.status !== "COMPLETED").length}</div>
              </div>
            </div>

            {/* MAP Action points table visual representation */}
            {allActionPoints.length === 0 ? (
              <div className="p-12 border border-zinc-800 border-dashed rounded-lg text-center font-sans text-zinc-500">
                No active mitigation action points found. Ingest circular items to generate action paths.
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse text-xs md:text-sm">
                  <thead>
                    <tr className="border-b border-zinc-800 font-mono text-zinc-400 uppercase">
                      <th className="py-3 px-4 font-semibold text-[10px] tracking-wider">Ticket</th>
                      <th className="py-3 px-4 font-semibold text-[10px] tracking-wider">Department</th>
                      <th className="py-3 px-4 font-semibold text-[10px] tracking-wider">Required Implementation Action</th>
                      <th className="py-3 px-4 font-semibold text-[10px] tracking-wider">Owner</th>
                      <th className="py-3 px-4 font-semibold text-[10px] tracking-wider">Timeline</th>
                      <th className="py-3 px-4 font-semibold text-[10px] tracking-wider">Status</th>
                      <th className="py-3 px-4 text-right font-semibold text-[10px] tracking-wider">Action</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-zinc-800/60 font-sans text-zinc-300">
                    {allActionPoints.map((ap) => (
                      <tr key={ap.jiraTicket} className="hover:bg-zinc-900/10 transition-colors">
                        <td className="py-4 px-4 font-mono font-bold text-blue-400">{ap.jiraTicket}</td>
                        <td className="py-4 px-4">
                          <span className="bg-zinc-950 border border-zinc-800 text-[10px] font-mono px-2 py-0.5 rounded font-bold uppercase text-zinc-300">
                            {ap.department}
                          </span>
                        </td>
                        <td className="py-4 px-4 text-zinc-350 font-normal leading-relaxed">{ap.actionRequired}</td>
                        <td className="py-4 px-4 text-zinc-400">{ap.owner}</td>
                        <td className="py-4 px-4 font-mono text-zinc-400">{ap.timelineDays} Days</td>
                        <td className="py-4 px-4">
                          {ap.status === "COMPLETED" ? (
                            <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-emerald-950/45 text-emerald-400 border border-emerald-800/40 uppercase">✓ COMPLETED</span>
                          ) : ap.status === "IN_PROGRESS" ? (
                            <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-amber-950/45 text-amber-400 border border-amber-800/40 uppercase">☇ IN PROGRESS</span>
                          ) : ap.status === "OVERDUE" ? (
                            <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-rose-950/45 text-rose-400 border border-rose-800/40 uppercase animate-pulse">✖ OVERDUE</span>
                          ) : (
                            <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-zinc-950/50 text-zinc-500 border border-zinc-800 uppercase">⌛ PENDING</span>
                          )}
                        </td>
                        <td className="py-4 px-4 text-right">
                          <button
                            onClick={() => toggleActionItemStatus(ap.jiraTicket)}
                            className={`px-3 py-1 rounded text-xs font-bold transition-all font-sans cursor-pointer ${ap.status === "COMPLETED" ? "bg-zinc-800 hover:bg-zinc-700 text-zinc-400 border border-zinc-700" : "bg-blue-600 hover:bg-blue-700 text-white"}`}
                          >
                            {ap.status === "COMPLETED" ? "Re-open" : "Mark Done"}
                          </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        )}

        {/* Dedicated standalone Topological Digital Twin layout viewport */}
        {activeTab === "twin-viz" && state && (
          <div className="flex flex-col gap-6 transition-all animate-fade-in" id="topological-twin-view">
            <DigitalTwin 
              nodes={state.digitalTwin.nodes} 
              links={state.digitalTwin.links}
              onTriggerDrift={handleTriggerDrift}
              onClearDrift={handleClearDrift}
            />
            
            {/* Quick explanatory cards matching Slide 7 */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mt-2">
              <div className="bg-zinc-900/30 border border-zinc-800 p-5 rounded-2xl">
                <span className="text-blue-400 font-mono text-xs uppercase font-bold block">Dependency Intelligence</span>
                <p className="text-xs text-zinc-400 mt-2 leading-relaxed">
                  Identifies all interconnected banking systems affected by incoming regulator circular parameters automatically.
                </p>
              </div>
              <div className="bg-zinc-900/30 border border-zinc-800 p-5 rounded-2xl">
                <span className="text-blue-400 font-mono text-xs uppercase font-bold block">Impact Analysis Matrix</span>
                <p className="text-xs text-zinc-400 mt-2 leading-relaxed">
                  Predicts downstream operational consequences of changes on session states and Ledger API databases in real-time.
                </p>
              </div>
              <div className="bg-zinc-900/30 border border-zinc-800 p-5 rounded-2xl">
                <span className="text-blue-400 font-mono text-xs uppercase font-bold block">Ownership Mapping</span>
                <p className="text-xs text-zinc-400 mt-2 leading-relaxed">
                  Automatically surfaces responsible operational engineering division owners for rapid coordination.
                </p>
              </div>
              <div className="bg-zinc-900/30 border border-zinc-800 p-5 rounded-2xl">
                <span className="text-blue-400 font-mono text-xs uppercase font-bold block">Organizational Reasoning</span>
                <p className="text-xs text-zinc-400 mt-2 leading-relaxed">
                  AI intelligence reasons comprehensively across the entire structural model, preventing fragmented task-level blind spots.
                </p>
              </div>
            </div>
          </div>
        )}

      </main>

      {/* Footer credits and system states */}
      <footer className="max-w-7xl mx-auto px-6 mt-16 pt-6 border-t border-zinc-800 text-center text-xs text-zinc-500 font-mono flex flex-col sm:flex-row sm:items-center justify-between gap-4" id="hud-footer">
        <div>
          SentinelX AI Compliance Intelligence — Designed for the future of continuous digital banking governance.
        </div>
        <div className="flex items-center gap-2 justify-center">
          <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 inline-block animate-ping" />
          <span>Post-audit memory indexing operational</span>
        </div>
      </footer>
    </div>
  );
}
